# Generated by Django 5.2.9 on 2025-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_team_rider_birth_date_rider_uci_id_rider_team_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rider",
            name="uniq_rider_name",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="uci_id",
        ),
        migrations.AlterField(
            model_name="rider",
            name="team",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
