# Generated by Django 5.2.9 on 2025-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0003_remove_rider_uniq_rider_name_remove_rider_uci_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onedayrace",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="race_profiles/"),
        ),
        migrations.AddField(
            model_name="onedayrace",
            name="profile_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stage",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="stage_profiles/"),
        ),
        migrations.AddField(
            model_name="stage",
            name="profile_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
