# Generated by Django 5.2.9 on 2026-01-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0004_onedayrace_profile_image_onedayrace_profile_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rider",
            options={"ordering": ("last_name", "first_name")},
        ),
    ]
