# Generated by Django 5.2.9 on 2026-01-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0005_alter_rider_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneDayRaceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                            ("nl", "Nederlands"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                        ],
                        max_length=2,
                    ),
                ),
                ("profile_text", models.TextField(blank=True, default="")),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="races.onedayrace",
                    ),
                ),
            ],
            options={
                "ordering": ["language"],
                "unique_together": {("race", "language")},
            },
        ),
        migrations.CreateModel(
            name="StageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                            ("nl", "Nederlands"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                        ],
                        max_length=2,
                    ),
                ),
                ("profile_text", models.TextField(blank=True, default="")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="races.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["language"],
                "unique_together": {("stage", "language")},
            },
        ),
    ]
