# Generated by Django 5.2.9 on 2026-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0006_onedayracetranslation_stagetranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="country",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
