# Generated by Django 5.2.9 on 2026-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("top", "Haut"),
                            ("sidebar", "Sidebar"),
                            ("bottom", "Bas"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(blank=True, null=True, upload_to="ads/")),
                ("target_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=100)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("slot", "priority", "-created_at"),
            },
        ),
    ]
