# Generated by Django 5.2.9 on 2025-12-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "France"),
                    ("BE", "Belgique"),
                    ("CH", "Suisse"),
                    ("ES", "Espagne"),
                    ("IT", "Italie"),
                    ("GB", "Royaume-Uni"),
                    ("NL", "Pays-Bas"),
                    ("US", "États-Unis"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_bike_brand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SPECIALIZED", "Specialized"),
                    ("TREK", "Trek"),
                    ("CANYON", "Canyon"),
                    ("PINARELLO", "Pinarello"),
                    ("CERVÉLO", "Cervélo"),
                    ("GIANT", "Giant"),
                    ("BMC", "BMC"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_rider_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POGACAR", "Tadej Pogačar"),
                    ("VINGEGAARD", "Jonas Vingegaard"),
                    ("VAN_DER_POEL", "Mathieu van der Poel"),
                    ("EVENEPOEL", "Remco Evenepoel"),
                    ("ROGLIC", "Primož Roglič"),
                    ("PIDCOCK", "Tom Pidcock"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UAE", "UAE Team Emirates"),
                    ("TVL", "Team Visma | Lease a Bike"),
                    ("IGD", "INEOS Grenadiers"),
                    ("SOQ", "Soudal Quick-Step"),
                    ("TBV", "BORA – hansgrohe"),
                    ("LTK", "Lidl–Trek"),
                    ("ADC", "Alpecin–Deceuninck"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("it", "Italiano"),
                ],
                max_length=8,
            ),
        ),
    ]
