# Generated by Django 5.2.9 on 2026-01-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_featured_badge"),
        ("badges", "0003_badge_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="featured_badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_by",
                to="badges.badge",
                verbose_name="Badge affiché",
            ),
        ),
    ]
