# Generated by Django 5.2.9 on 2026-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_featured_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("nl", "Nederlands"),
                    ("de", "Deutsch"),
                    ("it", "Italiano"),
                    ("pt", "Português"),
                ],
                max_length=8,
            ),
        ),
    ]
