# Generated by Django 5.2.9 on 2026-01-12 07:07

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
