# Generated by Django 5.2.9 on 2026-01-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0002_userbadge_uniq_user_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="PNG/SVG (si SVG: vérifier config).",
                null=True,
                upload_to="badge_icons/",
            ),
        ),
    ]
